config/routes.rb
Frust::Application.routes.draw do
  get "accounts/index"
  devise_for :users
root 'homes#index'

  devise_scope :user do
    get '/users/sign_out' => 'sessions#destroy'
  end

  resources :projectdetails
  resources :organizations

end

app/models/projectdetail.rb
class Projectdetail < ActiveRecord::Base
validates :proj_desc, presence: true
validates :biling_type, presence: true
validates :proj_name, presence: true, length: { maximum: 50 }

belongs_to :organization
belongs_to :user

def self.search(search,status,organization_id)
  if (search || status || organization_id)
    find(:all, :conditions => ['proj_name = ? OR status = ? OR organization_id = ?',search,status,organization_id])
  else
    find(:all)
  end
end

def self.count_by(count)
	find(:all, :conditions => ['status = ?', count]).count
end

#def self.status_count(count)
#	if (status)
#		find(:all, :where (status: "POC").count)
#end
#def self.search(search,status,client)
#  if (search || status || client)
#    find(:all, :conditions => ['name LIKE ? OR status LIKE ? OR client_id LIKE ?',search,status,client])
 # else
#    find(:all)
 # end
#end
#def projectdetails
#	@projectdetails ||= find_projectdetails
#end
#.where("proj_name LIKE ? OR status LIKE ?", "#{params[:search]}%", "#{params[:search]}%")
#projectdetails = Projectdetail.where("proj_name LIKE ?", "%#{search}%") 
#projectdetails = Projectdetail.where(status_id: status_id) 
#projectdetails = Projectdetail.where(org_id: org_id) 

end

app/controllers/projectdetails_controller.rb
class ProjectdetailsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :except => [:create]
  require 'will_paginate/array';
  before_action :set_projectdetail, only: [:show, :edit, :update, :destroy]
  

  def index
    #@projectdetails = projectdetail.all
    

    #search by method in model
    
    #@projectdetails = Projectdetail.paginate(:page => params[:page], :per_page => 5).order('dead_line_date asc').search(params[:search],params[:status],params[:organization_id])
    @projectdetails = Projectdetail.order('dead_line_date asc').paginate(:page => params[:page], :per_page => 5).search(params[:search],params[:status],params[:organization_id])
   

    #my method using kaminari
    #@projectdetails = Projectdetail



    #search not performed
    #@projectdetails = Projectdetail.order('dead_line_date asc').search(params[:search],params[:status],params[:org_id]).paginate(:page => params[:page], :per_page => 5)
    

    #experiment
    #@projectdetails = Projectdetail.where("org_id = ?",params[:org_id]).paginate(:page => params[:page])



    #.paginate(:page => params[:page])
    #using will_paginate
    #page(params[:page]).per(5).where("proj_name LIKE ? OR status LIKE ?", "#{params[:search]}%", "#{params[:search]}%")
    #paginate(:page => params[:page], :per_page => 5)
   # @projectdetails = Projectdetail.search(params[:search],params[:status],params[:org_id]).paginate(:page => params[:page])
    #@projectdetails = Projectdetail.paginate(:page => params[:page], :per_page => 5).order('dead_line_date asc')

    #{params[:search]}%", "#{params[:search]}%
    #@projects = Project.search(params[:search],params[:status],params[:client_id]).paginate(:page => params[:page])
    #@searches = User.joins([:requests]).where("name LIKE ? OR destination LIKE ?","#{params[:search]}%", "#{params[:search]}%")
    #@organizations = Organization.all
  
    #@projectdetails = Projectdetail.joins([:organizations]).where("proj_name LIKE ? OR status LIKE ? OR org_id LIKE?", "#{params[:search]}%", "#{params[:status]}%", "#{params[:org_id]}%")
  end

  def show
    #@projectdetail = Projectdetail.find(params[:id])
    #respond_to do |format|
     # format.html
     # format.pdf do
      #  pdf = ProjectdetailPdf.new(@projectdetail, view_context)
      #  send_data pdf.render, filename: "projectdetail_#{@projectdetail.proj_code}.pdf",
      #  type: "application/pdf",
       # dispostion: "inline"
  #end
#end
end

  def new
    @projectdetail = Projectdetail.new
  end

  def edit
  end

  def create
    @projectdetail = Projectdetail.new(projectdetail_params)
    respond_to do |format|
      if @projectdetail.save
        format.html { redirect_to @projectdetail, notice: 'Projectdetail was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @projectdetail.update(projectdetail_params) 
        format.html { redirect_to @projectdetail, notice: 'Projectdetail was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @projectdetail.destroy
    respond_to do |format|
      format.html { redirect_to projectdetails_url }
    end
  end

  private
    def set_projectdetail
      #@projectdetail = Projectdetail.find(params[:id])
    end

    def projectdetail_params
      params.require(:projectdetail).permit(:proj_name, :proj_code, :proj_desc, :biling_type, :start_date, :dead_line_date, :end_date, :github_url, :status, :organization_id)
    end
end

app/helpers/projectdetails_helper.rb
module ProjectdetailsHelper
end

app/views/projectdetails/_form.html.erb
<%= form_for @projectdetail, :html => { :class => 'form-horizontal' } do |f| %>
<% if @projectdetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projectdetail.errors.count, "error") %> prohibited this user input from being saved:</h2>

      <ul>
      <% @projectdetail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="span5">
      <div class="control-group">
    <%= f.label :Project_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :proj_name, placeholder: "Enter Project Name", :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Project_code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :proj_code, placeholder: "Enter Project Code", :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Project_description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :proj_desc, placeholder: "Enter Project Description", :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :Biling_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :biling_type, ['TNM', 'FIXED'], placeholder: "Select Biling type", :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :Start_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :start_date, placeholder: "Select Start Date" , 'data-behaviour' => 'datepicker', :id => 'datepicker', :class => 'text_field' %>
    </div>
  </div>

      <%= yield %></div>
      <div class="span5">
  <div class="control-group">
    <%= f.label :Dead_line_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :dead_line_date, placeholder: "Select Dead line date" , 'data-behaviour' => 'datepicker', :id => 'datepicker', :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :End_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :end_date, placeholder: "Select End date" , 'data-behaviour' => 'datepicker' , :id => 'datepicker', :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Github_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :github_url, placeholder: "Enter Github url ", :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Status, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :status, ['POC', 'KICK OFF', 'COMPLETED'], placeholder: "Select Status"  , :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
  <% if action_name == 'new' %> 
    <%= f.label :Organization_name, :class => 'control-label' %>
    <div class="controls">
    <%= f.collection_select :organization_id, Organization.all, :id, :org_name, placeholder: "Enter Organization_name", :class => 'text_field', include_blank: true %>
    </div>
    <% elsif action_name == 'edit' %>
    <%= f.label :Organization_name, :class => 'control-label' %>
    <div class="controls">
    <%= f.collection_select :organization_id, Organization.all, :id, :org_name, {}, {:disabled => "disabled"}  %> 
    </div>
    <% end %>
  </div>

  </div>
  </div>
  </div>
   
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), projectdetails_path, :class => 'btn' %>
  </div>
<% end %>

app/views/projectdetails/_projectdetail.html.erb
<tr>
        <td><%= link_to projectdetail.id, projectdetail_path(projectdetail) %></td>
        <td><%= projectdetail.proj_name %></td>
        <td><%= projectdetail.proj_code %></td>
        <td><%= projectdetail.proj_desc %></td>
        <td><%= projectdetail.biling_type %></td>
        <td><%= projectdetail.start_date %></td>
        <td><%= projectdetail.dead_line_date %></td>
        <td><%= projectdetail.end_date %></td>
        <td><%= projectdetail.github_url %></td>
        <td><%= projectdetail.status %></td>
        <td><%= Organization.find_by_id(projectdetail.organization.id).org_name %></td>
        <td><%= projectdetail.created_at %></td>
        <td>
          <%= link_to "Edit", edit_projectdetail_path(projectdetail), :class => 'btn btn-mini' %>
          <%= link_to "Destroy", projectdetail_path(projectdetail),
                      :method => :delete,
                      :data => { :confirm => 'Are you sure?' },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>

app/views/projectdetails/edit.html.erb
<%- model_class = Projectdetail -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projectdetails/index.html.erb
<%- model_class = Projectdetail -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <%= form_tag(:projectdetails, method: "get") do %>
        Enter Project Name
        <%= text_field_tag :search, params[:search] %>
        Enter status <%= select_tag(:status,options_for_select(['POC','KICK OFF','COMPLETED']))%>
        Enter Organization Name<%= select_tag(:organization_id, options_for_select(Organization.all.collect {|p| [ p.org_name, p.id ] })) %>
        <div align="center">
        <%= submit_tag "Search", class: "btn btn-primary" %>
      </div>
    <% end %>

    <tr>
      <th><%= model_class.human_attribute_name(:Id) %></th>
      <th><%= model_class.human_attribute_name(:Project_Name) %></th>
      <th><%= model_class.human_attribute_name(:Project_Code) %></th>
      <th><%= model_class.human_attribute_name(:Project_Desc) %></th>
      <th><%= model_class.human_attribute_name(:Billing_Type) %></th>
      <th><%= model_class.human_attribute_name(:Start_Date) %></th>
      <th><%= model_class.human_attribute_name(:Dead_line_Date) %></th>
      <th><%= model_class.human_attribute_name(:End_Date) %></th>
      <th><%= model_class.human_attribute_name(:Github_url) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:Organization_Name) %></th>
      <th><%= model_class.human_attribute_name(:Cretated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody id="projectdetail">
  <td>
   <%= render @projectdetails %>
    </tbody>
</table>
<div id="paginator">
    <%= will_paginate @projectdetails , :remote => true %>
</div>
<%= link_to "New", new_projectdetail_path, :class => 'btn btn-primary' %>

app/views/projectdetails/index.js.erb
$('#projectdetail').html('<%= escape_javascript render(@projectdetails) %>');
$('#paginator').html('<%= escape_javascript(paginate(@projectdetails, :remote => true).to_s) %>');

app/views/projectdetails/new.html.erb
<%- model_class = Projectdetail -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New Project%{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projectdetails/show.html.erb
<%- model_class = Projectdetail -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:proj_name) %>:</strong></dt>
  <dd><%= @projectdetail.proj_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:proj_code) %>:</strong></dt>
  <dd><%= @projectdetail.proj_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:proj_desc) %>:</strong></dt>
  <dd><%= @projectdetail.proj_desc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:biling_type) %>:</strong></dt>
  <dd><%= @projectdetail.biling_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_date) %>:</strong></dt>
  <dd><%= @projectdetail.start_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dead_line_date) %>:</strong></dt>
  <dd><%= @projectdetail.dead_line_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_date) %>:</strong></dt>
  <dd><%= @projectdetail.end_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:github_url) %>:</strong></dt>
  <dd><%= @projectdetail.github_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @projectdetail.status %></dd>

  <dt><strong><%= model_class.human_attribute_name(:organization_id) %></strong></dt>
  <dd><%= Organization.find_by_id(@projectdetail.organization_id).org_name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              projectdetails_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_projectdetail_path(@projectdetail), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              projectdetail_path(@projectdetail),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
              <%= link_to "Printable receipt", projectdetail_path(@projectdetail, format: "pdf") %>
</div>