config/routes.rb
Frust::Application.routes.draw do
  get "accounts/index"
  devise_for :users
root 'homes#index'

  devise_scope :user do
    get '/users/sign_out' => 'sessions#destroy'
  end

  resources :projectdetails
  resources :organizations

end

app/models/organization.rb
class Organization < ActiveRecord::Base
	validates :org_name, presence: true
	validates :org_country, presence: true, length: { maximum: 50 }

has_many :projectdetails
belongs_to :user
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
	before_action :authenticate_user!
	load_and_authorize_resource :except => [:create]
	before_action :set_organization, only: [:show, :edit, :update, :destroy]
	

	def show
	end

	def index
		@organizations = Organization.paginate(:page => params[:page], :per_page => 5)
	end

	def create
		@organization = Organization.new(organization_params)
    	respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization detail was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
	end

	def new
		#@organization = Organization.new
		#unauthorized! if cannot? :new, @organization
	end

	def update
		respond_to do |format|
      if @organization.update(organization_params) 
        format.html { redirect_to @organization, notice: 'Organization detail was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
	end

	def destroy
		 @organization.destroy
    	respond_to do |format|
      	format.html { redirect_to organizations_url }
    end
	end
	
	private 

	def organization_params
		params.require(:organization).permit(:org_name, :org_country)
	end

	def set_organization
		#@organization = Organization.find(params[:id])
	end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for @organization, :html => { :class => 'form-horizontal' } do |f| %>
<% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this data input from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="span5">
      <div class="control-group">
    <%= f.label :Organization_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :org_name, placeholder: "Enter Organization Name", :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Country, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :org_country,['india', 'United states', 'Australia', 'United Kingdom', 'Iran' ] , placeholder: "choose country", :class => 'text_field' %>
    </div>
  </div>
  </div>
  </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projectdetails_path, :class => 'btn' %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<%- model_class = Organization -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/organizations/index.html.erb
<%- model_class = Organization -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:Id) %></th>
      <th><%= model_class.human_attribute_name(:Organization_Name) %></th>
      <th><%= model_class.human_attribute_name(:Organization_Country) %></th>
      

      
      <th><%= model_class.human_attribute_name(:POC) %></th>
      <th><%= model_class.human_attribute_name(:KICK_OFF) %></th>
      <th><%= model_class.human_attribute_name(:COMPLETED) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody id="projectdetail">
  <% @organizations.each do |f| %>
 <tr>
        <td><%= link_to f.id, organization_path(f) %></td>
        <td><%= f.org_name %></td>
        <td><%= f.org_country %></td>
        <td><%= f.projectdetails.count_by('POC')%></td>
        <td><%= f.projectdetails.count_by('KICK_OFF')%></td>
        <td><%= f.projectdetails.count_by('COMPLETED') %></td>
        <td>
          <%= link_to "Edit", edit_organization_path(f), :class => 'btn btn-mini' %>
          <% if f.projectdetails.any? %>

          <% else %>
          <%= link_to "Destroy", organization_path(f
            ),
                      :method => :delete, 
                      :data => { :confirm => 'Are you sure?' }, 
                      :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </td>
      </tr>
<% end %>
    </tbody>
</table>
<div id="paginator", align="right">
    <%= will_paginate @organizations, :remote => true %>
</div>
<%= link_to "New", new_organization_path, :class => 'btn btn-primary' %>

app/views/organizations/index.js.erb
$('#projectdetail').html('<%= escape_javascript render(@organizations) %>');
$('#paginator').html('<%= escape_javascript(paginate(@organizations, :remote => true).to_s) %>');

app/views/organizations/new.html.erb
<%- model_class = Organization -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/organizations/show.html.erb
<%- model_class = Organization -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:org_name) %>:</strong></dt>
  <dd><%= @organization.org_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:org_country) %>:</strong></dt>
  <dd><%= @organization.org_country %></dd>
</dl>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              organizations_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_organization_path(@organization), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              organization_path(@organization),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>